name: Artefacts

on: [push]

env:
  ARTEFACT_NAME: my_artefact
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Upload the artefact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTEFACT_NAME }}
          path: .
