name: Artefacts

on: [push]

env:
  ARTEFACT_NAME: my_artefact
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Upload the artefact
        uses: actions/upload-artefact@v2
        with:
          name: ${{ env.ARTEFACT_NAME }}
          path: .
